Add npm-dependency-duplications action step
vazco/open-standards pull request #2
Opened 2022-01-28 15:13 UTC by Monteth

2022-05-05 14:51 UTC, radekmie requested changes

2022-05-05 14:51 UTC, radekmie commented on actions/npm-dependency-duplications/action.yml
> +  using: 'node16'
Can this be parametrized on the callee side?

2022-05-05 14:51 UTC, radekmie commented on actions/npm-dependency-duplications/action.yml
> +name: 'Npm security audit'
I'd rather use "npm" everywhere as that's the suggested name.

2022-05-13 12:39 UTC, Monteth commented on actions/npm-dependency-duplications/action.yml
> +  using: 'node16'
I am pretty sure we don't want to configure that on the the callee side, as it's only for setting the execution environment for our `index.js` file [docs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing). You probably wanted to configure the npm version for `npm dedupe` (and `npm audit`), but we are calling npm commands in existing environment.
You can configure which node version you want to use by running `actions/setup-node` with desired parameters before using our action. 

Example:
```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 15
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 15
      - uses: ./actions/npm-dependency-duplications
        with:
          path: ./actions/npm-dependency-duplications/test/positive
```

will run `npm dedupe` check with node@15.

2022-05-13 12:56 UTC, radekmie commented on actions/npm-dependency-duplications/action.yml
> +  using: 'node16'
That was exactly my point. Great!

2022-05-13 12:56 UTC, radekmie approved these changes

2022-05-31 10:40 UTC, wadamek65 approved these changes

2022-05-31 10:40 UTC, wadamek65 commented on .github/workflows/check_dependency_duplications.yml
> +      - name: Set Node.js 16
Same suggestion for other places too:
```suggestion
      - name: Set up Node.js 16
```

2022-05-31 10:40 UTC, wadamek65 commented on .github/workflows/check_dependency_duplications.yml
> +name: "npm-dependency-duplications test"
nitpick: use single quotes for consistency or remove them if they are not needed.

2022-05-31 10:40 UTC, wadamek65 commented on .github/workflows/check_dependency_vulnerabilities.yml
> +name: "npm-dependency-vulnerabilities test"
Same as above.

2022-05-31 10:40 UTC, wadamek65 commented on .gitignore
> +
Was this on purpose? Also consider adding the vscode directories since `.idea` is here already.
```suggestion
```

2022-06-10 12:38 UTC, merged